[project]
name = "engi-hackathon-mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "astral>=3.2",
    "httpx>=0.28.1",
    "mcp>=1.21.1",
]
